export const filmsModule = {
  state: () => ({
    films: [
      { id: "1", name: 'Звонок', genre: 'Ужасы', rating: 5, desc: 'Телефонный звонок раздаётся после просмотра некой загадочной видеокассеты. Жертве даётся ровно семь дней, а после следует неминуемая смерть. Журналистка Рэйчел расследует загадочные смерти молодых людей, и случайно кассета-убийца попадает в руки к её маленькому сыну, над которым теперь нависает смертельная угроза. У женщины есть только семь дней, чтобы разобраться в происходящем и спасти своего мальчика.', img:'./assets/logo.png',
      dates: [
        { date: "23.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "24.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "25.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "26.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "27.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "28.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "29.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },      
      ] },
      { id: "2", name: 'Американский пирог', genre: 'Комедия', rating: 5, desc: 'На вечеринке четверо старшеклассников, Джим, Кевин, Финч и Оз, выясняют, что никто из них еще не имел сексуального опыта с девушками. Приятели считают, что с коллективной девственностью надо обязательно расстаться до того, как они переступят порог колледжа. На носу школьный выпускной бал, и у друзей осталось совсем мало времени на то, чтобы выполнить задуманное.', img:'./assets/logo.png',
      dates: [
        { date: "23.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "24.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "25.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "26.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "27.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "28.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "29.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },      
      ] },
      { id: "3", name: 'Реквием по мечте', genre: 'Драма', rating: 5, desc: 'Каждый стремится к своей заветной мечте. Сара Голдфарб мечтала сняться в известном телешоу, ее сын Гарольд с другом Тайроном — сказочно разбогатеть, подруга Гарольда Мэрион грезила о собственном модном магазине, но на их пути были всевозможные препятствия. Все они выбирают неочевидные пути достижения своих целей, и мечты по-прежнему остаются недостижимыми, а жизни героев рушатся безвозвратно.', img:'./assets/logo.png',
      dates: [
        { date: "23.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "24.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "25.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "26.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "27.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "28.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "29.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },      
      ] },
      { id: "4", name: 'Невидимый гость', genre: 'Триллер', rating: 3, desc: 'Молодого бизнесмена Адриана Дориа обвиняют в убийстве любовницы, и он решает воспользоваться услугами Вирджинии Гудман, лучшего в стране специалиста по выходу из самых сложных ситуаций. Адриан содержится под домашним арестом, а завтра состоится судебное заседание, поэтому вечером к нему приходит Вирджиния, чтобы придумать наилучшую стратегию защиты. Для неё это последнее дело, и она не собирается его проигрывать.', img:'./assets/logo.png', 
      dates: [
        { date: "23.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "24.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "25.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "26.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "27.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "28.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },
        { date: "29.03.2023", places: [{ vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true}, { vacant: true} ] },      
      ] }
    ],
  }),
  getters: {
    FILMS(state) {
      return state.films
    }
  },
  mutations: {},
  actions: {},
  namespaced: true,
};
